### 
GET http://localhost:8080/api/users/

###
GET http://localhost:8080/api/users/345

### change role
PUT http://localhost:8080/api/users/premium/64eba5eb9fa0b87e89f04573/


###
DELETE http://localhost:8080/api/users/64eba3191d85b6cbcb6b8dc4